# SPDX-FileCopyrightText: 2026 Hari Srinivasan <harisrini21@gmail.com>
# SPDX-License-Identifier: Apache-2.0

"""OpenCode telemetry plugin source."""

from __future__ import annotations

OPENCODE_PLUGIN_VERSION = "5"

OPENCODE_PLUGIN_SOURCE = """// Observal telemetry plugin for OpenCode
// Auto-generated by `observal doctor patch`
// Do not edit manually, regenerated on upgrade.

import { chmodSync, existsSync, mkdirSync, readFileSync, readdirSync, renameSync, statSync, unlinkSync, writeFileSync } from "fs";
import { createHash } from "crypto";
import { join } from "path";

const OBSERVAL_PLUGIN_VERSION = "__OPENCODE_PLUGIN_VERSION__";
const HOME = process.env.HOME || process.env.USERPROFILE || "~";
const OBSERVAL_DIR = join(HOME, ".observal");
const CONFIG_PATH = join(OBSERVAL_DIR, "config.json");
const LOCKFILE_PATH = join(OBSERVAL_DIR, "lockfile.json");
const OUTBOX_DIR = join(OBSERVAL_DIR, "opencode_session_outbox");
const MAX_OUTBOX_BYTES = 256 * 1024 * 1024;
const ACKED_STATE_TTL_MS = 7 * 24 * 60 * 60 * 1000;
const BUILTIN_AGENTS = new Set(["build", "plan", "general", "explore", "scout", "compaction", "title", "summary"]);

function loadConfig() {
  try {
    if (!existsSync(CONFIG_PATH)) return null;
    const cfg = JSON.parse(readFileSync(CONFIG_PATH, "utf-8"));
    const token = cfg.api_key || cfg.access_token;
    if (!cfg.server_url || !token || !cfg.user_id) return null;
    return { server_url: String(cfg.server_url).replace(/\\/$/, ""), token, user_id: String(cfg.user_id) };
  } catch {
    return null;
  }
}

function loadLockfile() {
  try {
    if (!existsSync(LOCKFILE_PATH)) return null;
    return JSON.parse(readFileSync(LOCKFILE_PATH, "utf-8"));
  } catch {
    return null;
  }
}

function resolveAgent(agentName, directory) {
  if (!agentName || BUILTIN_AGENTS.has(agentName)) return null;
  const agents = loadLockfile()?.harnesses?.opencode?.agents;
  if (!Array.isArray(agents)) return null;
  const matches = agents.filter((agent) => agent?.name === agentName || agent?.id === agentName);
  if (matches.length === 0) return null;
  const chosen =
    matches.find((agent) => agent?.scope === "project" && agent?.directory === directory) ||
    matches.find((agent) => agent?.scope !== "project") ||
    matches[0];
  if (!chosen?.id) return null;
  return { id: chosen.id, version: chosen.version || null };
}

async function log(client, level, message, extra = {}) {
  try {
    await client.app.log({ body: { service: "observal", level, message, extra } });
  } catch {
  }
}

function statePath(sessionId) {
  const name = createHash("sha256").update(sessionId).digest("hex");
  return join(OUTBOX_DIR, `${name}.json`);
}

function newSessionState(sessionId) {
  return {
    version: 1,
    sessionId,
    agentName: null,
    acknowledgedLine: -1,
    checkpointRecovered: false,
    pending: null,
    attempts: 0,
    updatedAt: Date.now(),
  };
}

function loadSessionState(sessionId) {
  const path = statePath(sessionId);
  if (!existsSync(path)) return newSessionState(sessionId);
  let state;
  try {
    state = JSON.parse(readFileSync(path, "utf-8"));
  } catch {
    try { renameSync(path, `${path}.corrupt.${Date.now()}`); } catch { }
    return newSessionState(sessionId);
  }
  if (state?.version !== 1 || state?.sessionId !== sessionId) {
    try { renameSync(path, `${path}.corrupt.${Date.now()}`); } catch { }
    return newSessionState(sessionId);
  }
  if (typeof state.checkpointRecovered !== "boolean") state.checkpointRecovered = false;
  return state;
}

function outboxBytes(excludePath) {
  if (!existsSync(OUTBOX_DIR)) return 0;
  let total = 0;
  for (const name of readdirSync(OUTBOX_DIR)) {
    const path = join(OUTBOX_DIR, name);
    if (path === excludePath || !name.endsWith(".json")) continue;
    try { total += statSync(path).size; } catch { }
  }
  return total;
}

function saveSessionState(state) {
  mkdirSync(OUTBOX_DIR, { recursive: true });
  const path = statePath(state.sessionId);
  state.updatedAt = Date.now();
  const serialized = JSON.stringify(state);
  if (outboxBytes(path) + Buffer.byteLength(serialized) > MAX_OUTBOX_BYTES) {
    throw new Error("Observal OpenCode durable outbox is full; records were not discarded");
  }
  const temporary = `${path}.${process.pid}.${Date.now()}.tmp`;
  writeFileSync(temporary, serialized, { mode: 0o600 });
  renameSync(temporary, path);
  try { chmodSync(path, 0o600); } catch { }
}

function pruneOutbox() {
  if (!existsSync(OUTBOX_DIR)) return;
  const cutoff = Date.now() - ACKED_STATE_TTL_MS;
  for (const name of readdirSync(OUTBOX_DIR)) {
    if (!name.endsWith(".json")) continue;
    const path = join(OUTBOX_DIR, name);
    try {
      const state = JSON.parse(readFileSync(path, "utf-8"));
      if (!state.pending && Number(state.updatedAt || 0) < cutoff) unlinkSync(path);
    } catch {
      // Fail closed: keep corrupt or unreadable files for manual recovery.
    }
  }
}

function applyAcknowledgement(state, acknowledgement) {
  if (!state.pending) return true;
  const acknowledgedLine = acknowledgement?.acknowledged_line;
  if (!Number.isInteger(acknowledgedLine) || acknowledgedLine < state.pending.endLine) return false;
  state.acknowledgedLine = Math.max(state.acknowledgedLine, acknowledgedLine);
  state.checkpointRecovered = true;
  state.pending = null;
  state.attempts = 0;
  saveSessionState(state);
  return true;
}

async function pushToServer(client, payload, config) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);
  try {
    const response = await fetch(`${config.server_url}/api/v1/ingest/session`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${config.token}`,
      },
      body: JSON.stringify(payload),
      signal: controller.signal,
    });
    if (!response.ok) {
      await log(client, "warn", "Observal ingest rejected OpenCode session", { status: response.status, session_id: payload.session_id });
      return null;
    }
    const acknowledgement = await response.json();
    if (!Number.isInteger(acknowledgement?.acknowledged_line)) {
      await log(client, "warn", "Observal ingest returned no OpenCode acknowledgement", { session_id: payload.session_id });
      return null;
    }
    return acknowledgement;
  } catch (error) {
    await log(client, "error", "Observal ingest failed for OpenCode session", { session_id: payload.session_id, error: String(error) });
    return null;
  } finally {
    clearTimeout(timeout);
  }
}

async function recoverServerCheckpoint(client, state) {
  if (state.checkpointRecovered) return false;
  const config = loadConfig();
  if (!config) return false;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);
  try {
    const url = new URL(`${config.server_url}/api/v1/ingest/session/checkpoint`);
    url.searchParams.set("session_id", state.sessionId);
    url.searchParams.set("harness", "opencode");
    const response = await fetch(url, {
      headers: { "Authorization": `Bearer ${config.token}` },
      signal: controller.signal,
    });
    if (!response.ok) return false;
    const checkpoint = await response.json();
    if (!Number.isInteger(checkpoint?.acknowledged_line)) return false;
    const needsReplay = Boolean(state.pending && state.pending.startLine > checkpoint.acknowledged_line + 1);
    state.acknowledgedLine = checkpoint.acknowledged_line;
    state.checkpointRecovered = true;
    if (needsReplay) state.pending = null;
    saveSessionState(state);
    return needsReplay;
  } catch (error) {
    await log(client, "warn", "OpenCode server checkpoint recovery failed", { session_id: state.sessionId, error: String(error) });
    return false;
  } finally {
    clearTimeout(timeout);
  }
}

function pendingPayload(state) {
  const pending = state.pending;
  const payload = {
    session_id: state.sessionId,
    harness: "opencode",
    lines: pending.lines,
    agent_id: pending.agentId,
    agent_version: pending.agentVersion,
    start_offset: pending.startLine,
    hook_event: "session.idle",
    final: pending.final,
  };
  if (pending.final) {
    payload.total_line_count = pending.endLine + 1;
    payload.total_offset = 0;
    payload.session_hash = pending.sessionHash;
    payload.hashed_line_count = pending.hashedLineCount;
  }
  return payload;
}

async function deliverPending(client, state) {
  if (!state.pending) return true;
  const config = loadConfig();
  if (!config) {
    await log(client, "warn", "missing Observal config");
    return false;
  }
  if (state.pending.destination !== config.server_url || state.pending.userId !== config.user_id) {
    await log(client, "error", "OpenCode outbox belongs to a different Observal login", { session_id: state.sessionId });
    return false;
  }
  const acknowledgement = await pushToServer(client, pendingPayload(state), config);
  if (!acknowledgement) {
    state.attempts = Number(state.attempts || 0) + 1;
    saveSessionState(state);
    return false;
  }
  return applyAcknowledgement(state, acknowledgement);
}

async function drainStoredOutbox(client) {
  if (!existsSync(OUTBOX_DIR)) return;
  for (const name of readdirSync(OUTBOX_DIR)) {
    if (!name.endsWith(".json")) continue;
    const path = join(OUTBOX_DIR, name);
    try {
      const state = JSON.parse(readFileSync(path, "utf-8"));
      if (state?.version !== 1 || !state?.sessionId) throw new Error("invalid durable state");
      sessionState.set(state.sessionId, state);
      if (state.pending) await deliverPending(client, state);
    } catch (error) {
      await log(client, "error", "OpenCode durable outbox cannot be drained", { path, error: String(error) });
    }
  }
}

function messagesToLines(messages) {
  const lines = [];
  for (const msg of messages) {
    const info = msg.info || msg;
    const parts = msg.parts || [];
    const content = [];
    for (const part of parts) {
      if (part.type === "text") {
        content.push({ type: "text", text: part.text || "" });
      } else if (part.type === "tool-invocation" || part.type === "tool_use") {
        content.push({ type: "tool_use", id: part.toolInvocationId || part.id || "", name: part.toolName || part.name || "", input: part.args || part.input || {} });
      } else if (part.type === "tool-result" || part.type === "tool_result") {
        content.push({ type: "tool_result", tool_use_id: part.toolInvocationId || part.tool_use_id || "", content: part.result || part.content || "" });
      } else if (part.type === "reasoning" || part.type === "thinking") {
        content.push({ type: "thinking", thinking: part.text || part.thinking || "" });
      }
    }
    const role = info.role || "assistant";
    let ts = "";
    if (info.createdAt && typeof info.createdAt === "string") { ts = info.createdAt; }
    else if (info.time && typeof info.time === "object" && info.time.created) { ts = new Date(info.time.created).toISOString(); }
    else if (info.time && typeof info.time === "string") { ts = info.time; }
    else if (info.timestamp && typeof info.timestamp === "string") { ts = info.timestamp; }
    const line = {
      type: role === "user" ? "user" : "assistant",
      timestamp: ts,
      uuid: info.id || "",
      parentUuid: info.parentID || info.parentId || "",
      message: { role, content, model: info.modelID || info.model || "" },
    };
    if (info.tokens || info.usage) {
      const usage = info.tokens || info.usage || {};
      line.message.usage = {
        input_tokens: usage.input || usage.inputTokens || 0,
        output_tokens: usage.output || usage.outputTokens || 0,
        cache_read_input_tokens: usage.cacheRead || usage.cacheReadTokens || 0,
        cache_creation_input_tokens: usage.cacheWrite || usage.cacheWriteTokens || 0,
      };
    }
    lines.push(JSON.stringify(line));
  }
  return lines;
}

function sessionIdFrom(event) {
  return event?.properties?.sessionID || event?.properties?.info?.id || "";
}

function agentFrom(event) {
  return event?.properties?.agent || event?.properties?.info?.agent || "";
}

const sessionState = new Map();
function getState(sessionId) {
  if (!sessionState.has(sessionId)) sessionState.set(sessionId, loadSessionState(sessionId));
  return sessionState.get(sessionId);
}

export const ObservalPlugin = async ({ client, directory }) => {
  const pendingPush = new Map();
  pruneOutbox();
  await drainStoredOutbox(client);

  return {
    event: async ({ event }) => {
      const sessionId = sessionIdFrom(event);
      let state = null;
      if (sessionId) {
        try {
          state = getState(sessionId);
        } catch (error) {
          await log(client, "error", "OpenCode durable outbox cannot be read", { session_id: sessionId, error: String(error) });
          return;
        }
      }

      if (event?.type === "session.created" || event?.type === "session.updated" || event?.type === "session.next.agent.switched") {
        const agentName = agentFrom(event);
        const agent = resolveAgent(agentName, directory);
        if (state && agent) {
          state.agentName = agentName;
          saveSessionState(state);
          pendingPush.set(sessionId, true);
        }
      }

      if (event?.type === "message.updated" && sessionId) pendingPush.set(sessionId, true);

      if (event?.type === "session.idle") {
        if (!state?.agentName) return;
        const agent = resolveAgent(state.agentName, directory);
        if (!agent) return;

        try {
          if (await recoverServerCheckpoint(client, state)) pendingPush.set(sessionId, true);
          if (!(await deliverPending(client, state))) return;
          if (!pendingPush.get(sessionId)) return;

          const messagesResult = await client.session.messages({ path: { id: sessionId } });
          const messages = messagesResult?.data || messagesResult || [];
          if (!Array.isArray(messages) || messages.length === 0) return;
          const startLine = state.acknowledgedLine + 1;
          if (startLine >= messages.length) {
            pendingPush.delete(sessionId);
            return;
          }
          const lines = messagesToLines(messages.slice(startLine));
          if (lines.length === 0) return;
          const config = loadConfig();
          if (!config) {
            await log(client, "warn", "missing Observal config");
            return;
          }
          const isFinal = event?.properties?.final === true || event?.properties?.reason === "completed";
          const allLines = isFinal ? messagesToLines(messages) : [];
          const sessionHash = isFinal
            ? createHash("sha256").update(
                allLines.map((line) => `${createHash("sha256").update(line).digest("hex")}\n`).join("")
              ).digest("hex")
            : null;
          state.pending = {
            destination: config.server_url,
            userId: config.user_id,
            startLine,
            endLine: startLine + lines.length - 1,
            lines,
            agentId: agent.id,
            agentVersion: agent.version,
            final: isFinal,
            sessionHash,
            hashedLineCount: isFinal ? allLines.length : null,
          };
          saveSessionState(state); // Durable before network delivery.
          pendingPush.delete(sessionId);
          await deliverPending(client, state);
        } catch (error) {
          await log(client, "error", "OpenCode plugin failed to export session", { session_id: sessionId, error: String(error) });
        }
      }
    },
  };
};
""".replace("__OPENCODE_PLUGIN_VERSION__", OPENCODE_PLUGIN_VERSION)
