"""add agent team access

Revision ID: e8e63ca6d74e
Revises: 0018
Create Date: 2026-04-25 19:29:53.469407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e63ca6d74e'
down_revision: Union[str, Sequence[str], None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS agent_team_access CASCADE;")
    op.create_table('agent_team_access',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('agent_id', sa.UUID(), nullable=False),
        sa.Column('group_name', sa.String(length=255), nullable=False),
        sa.Column('permission', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('visibility', sa.Enum('public', 'private', name='agentvisibility'), nullable=False, server_default='private'))
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_column('agents', 'is_private')
    op.drop_index(op.f('ix_hook_listings_bundle_id'), table_name='hook_listings')
    op.drop_index(op.f('ix_mcp_listings_bundle_id'), table_name='mcp_listings')
    op.drop_index(op.f('ix_prompt_listings_bundle_id'), table_name='prompt_listings')
    op.drop_index(op.f('ix_sandbox_listings_bundle_id'), table_name='sandbox_listings')
    op.drop_index(op.f('ix_skill_listings_bundle_id'), table_name='skill_listings')
    op.drop_index(op.f('ix_users_email_lower'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email_lower'), 'users', [sa.literal_column('lower(email::text)')], unique=True)
    op.create_index(op.f('ix_skill_listings_bundle_id'), 'skill_listings', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_sandbox_listings_bundle_id'), 'sandbox_listings', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_prompt_listings_bundle_id'), 'prompt_listings', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_mcp_listings_bundle_id'), 'mcp_listings', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_hook_listings_bundle_id'), 'hook_listings', ['bundle_id'], unique=False)
    op.add_column('agents', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default='true'))
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.drop_column('agents', 'visibility')
    op.drop_table('agent_team_access')
    # ### end Alembic commands ###
