# SPDX-FileCopyrightText: 2026 Observal Contributors
# SPDX-FileCopyrightText: 2026 amogh-dongre <amoghdongre16@gmail.com>
# SPDX-License-Identifier: Apache-2.0


repositoryID: bcccc095-d7e6-4ae3-b40c-b5c2b6fb2f80
owners:
  - name: Observal
    email: harisrini21@gmail.com
